Repository asciidoctor/asciidoctor-reveal.js, pull requests merged in 2019-12, with the labels that each got.

#267 fix: only use lowercase asciidoc attributes
  templates/document.html.slim
  test/doctest/revealjs-features.html
Labels: bug, critical

#247 Dropping Ruby 2.1 and 2.2 (End of Life)
  .travis.yml
Labels: compliance

#269 feat: support data-background-opacity via background-opacity
  templates/document.html.slim
  templates/section.html.slim
Labels: compliance

#297 Alternate converter name: reduces surprises and backward compatible
  Rakefile
  examples/multi-destination-content.adoc
Labels: enhancement
