Repository asciidoctor/asciidoctor-reveal.js, pull requests merged in 2020-02, with the labels that each got.

#322 Changes required to make debugging work again
  CHANGELOG.adoc
  HACKING.adoc
  asciidoctor-revealjs.gemspec
Labels: bug

#325 Title slide opacity attribute name aligned with all other values
  CHANGELOG.adoc
  templates/document.html.slim
  templates/title_slide.html.slim
Labels: compliance

#320 resolves #21 load highlight.js from a CDN
  .gitignore
  HACKING.adoc
  README.adoc
  examples/source-highlightjs-html.adoc
  examples/source-highlightjs-languages.adoc
  examples/source-highlightjs.adoc
  lib/asciidoctor-revealjs/highlightjs.rb
  templates/document.html.slim
  test/doctest/fragments.html
  test/doctest/history-hash.html
  test/doctest/history-regression-tests.html
  test/doctest/history.html
  test/doctest/links-preview.html
  test/doctest/revealjs-plugin-activation.html
  test/doctest/revealjs-plugins.html
  test/doctest/source-highlightjs-html.html
  test/doctest/source-highlightjs-languages.html
  test/doctest/source-highlightjs.html
  test/doctest/theme-custom.html
Labels: enhancement

#334 Cancel Asciidoctor line-height in highlight.js table (fixes #331)
  examples/source-emphasis.adoc
  examples/source-emphasis.css
  templates/asciidoctor-compatibility.css
  test/doctest/source-emphasis.html
Labels: bug

#335 Cosmetic improvements to callout lists
  examples/source-emphasis.adoc
  templates/asciidoctor-compatibility.css
  test/doctest/source-emphasis.html
Labels: compliance

#337 doc: added link to AsciidoctorJ reveal.js
  HACKING.adoc
  README.adoc
Labels: enhancement

#339 Fixes crash with highlight.js and listing blocks w/o source
  examples/source-highlightjs.adoc
  templates/listing.html.slim
  test/doctest/source-highlightjs.html
Labels: bug

#340 Added is-vcentered to our columns options
  examples/grid-layout.adoc
  templates/asciidoctor-compatibility.css
  test/doctest/grid-layout.html
Labels: compliance, enhancement
